### ISSUE TITLE
テスト実行時のmock機能

### ISSUE THREAD

**Issue by kojirock5260** [write-blog-every-week/write-blog-every-week-remind#2]
lambda経由で実行されるため、ローカルからテストで実行する場合、lambda経由実行ではないようにmain.goのコードを修正している。

ローカルから実行する場合も毎回コード修正しなくても実行できるようにしたい。

素直に別ファイル用意したほうがよい？

**Comment by budougumi0617** [comment]
`aws-sam-cli`(npmでインストールする）使ってDynamo DB Local使う感じで良いですかね？

https://github.com/awslabs/aws-sam-cli
https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/DynamoDBLocal.Docker.html

**Comment by kojirock** [comment]
確認しました。
こういった機能あるのですね！
使ったことなく知りませんでした。。
はい。使用していただいてかまいません！
ありがとうございます 🙇 :

**Comment by kojirock5260** [comment]
一旦コチラはclose
