### ISSUE TITLE
各テストコード

### ISSUE THREAD

**Issue by kojirock5260** [write-blog-every-week/write-blog-every-week-remind#3]
とにかく作ろう精神でテストコードガン無視していたので、テストコード書きたい。

**Comment by kojirock** [comment]
@budougumi0617 
@kdnakt 

#5 のissueにも関わってくるのですが、dynamoDBを使用した際のtestはどのように書けばよいでしょうか？
日付のテストと同じくモックを用意して対応するような形でしょうか？

**Comment by kojirock** [comment]
https://github.com/write-blog-every-week/write-blog-every-week-remind/issues/2#issuecomment-445093332

べつissueで紹介してくれておりました 🙇 
失礼しました 🙇

**Comment by budougumi0617** [comment]
integration test書く時はローカルでDynamo DBのインスタンス立ち上げたほうが良いと思いますが、
ユニットテストレベルならDBへの依存切っておいてモック注入するのがベターかなと思います。

いちおうCircleCI回すときにDockerインスタンスを立ち上げるのも可能です。

**Comment by kojirock5260** [comment]
内容がざっくりとしているので、一旦クローズして、該当ファイルのテストコードという形で、new issueを作成します。
